### ISSUE TITLE
property expressions not possible

### ISSUE THREAD

**Issue by mvaneijken** [ili101/Join-Object#11]
Join-Object of RamblingCookieMonster has an option to add rightproperties using a expression like:
`Join-Object -Left $L -Right $R -LeftJoinProperty Name -RightJoinProperty Manager -Type AllInBoth -RightProperties @{ N = "DeptName"; expression = {$_.Name} }`

That does not seem to work in this join-object function. 

Background question, I'd like to have the join attribute from both sides in the result, so that I'm able to do a filter on it where the right join property value is $null.

**Comment by ili101** [comment]
I didn't noticed that his function can do that, I do have the option to rename it like `-RightProperties @{ OldName = 'DeptName' }` dose this help you or do you actually need to do something more complicated then this renaming example?

Regarding the other question you can use `-KeepRightJoinProperty` to have both sides join columns (so it will be null if there was noting to join).
Or you can use `-AddKey 'The Join Key'` that will add a column with the join property so you have the join key in a single column (when using "-Type AllInBoth").

**Comment by mvaneijken** [comment]
The KeepRightJoinProperty did eventually what I was aiming for. I missed it somehow. Therefor I was trying to to it using the RightProperties expression. That worked with the original join-object of RamblingCookieMonster and not in this version.

For me it's fixed, but if you're aiming to have the same functionality as the original one, then this is something to add.
