### ISSUE TITLE
Example of -comparer

### ISSUE THREAD

**Issue by maysara** [ili101/Join-Object#15]
Hello, and thank you for this beutiful piece of code.

Can you please include an example of how -comparer is used and how the  custom [EqualityComparer] is passed ?

**Comment by ili101** [comment]
Hi, thank you

I have sort of an example in [Join-Object.Tests.ps1](https://github.com/ili101/Join-Object/blob/1e2ac7a9a5283d175541f29999caa3ff97fdbf7b/Tests/Join-Object.Tests.ps1)
Here the same thing cleaned up a little:
``` powershell
$DataTable = [Data.DataTable]::new('Test')
$null = $DataTable.Columns.Add('IDD', [System.Int32])
$null = $DataTable.Columns.Add('Name')
$null = $DataTable.Columns.Add('Junk')
$null = $DataTable.Columns.Add('IntT', [System.Int32])
$null = $DataTable.Rows.Add(1, 'A', 'AAA', 5)
$null = $DataTable.Rows.Add(3, 'C', 'S3', $null)
$null = $DataTable.Rows.Add(4, 'D', $null, $null)
    
$PSCustomObjectKeyArray = @(
    [PSCustomObject]@{ID = 1, 2, 3 ; Sub = 'S1' ; IntO = 6 }
    [PSCustomObject]@{ID = 4 ; Sub = 'S4' ; IntO = $null }
)

Class EqualityComparerMy : Collections.Generic.EqualityComparer[Object] {
    [bool] Equals([Object]$Object1 , [Object]$Object2) {
        if ($Object1 -contains $Object2 -or $Object1 -in $Object2) {
            return $true
        }
        else {
            return $false
        }
    }
    [int] GetHashCode([Object]$Object) {
        return 1
    }
}

$Params = @{
    Left                   = $DataTable
    Right                  = $PSCustomObjectKeyArray
    LeftJoinProperty       = 'IDD'
    RightJoinProperty      = 'ID'
    ExcludeRightProperties = 'Junk'
    Prefix                 = 'R_'
    RightJoinScript        = [System.Func[Object, Object]] { param ($Line) $Line.ID }
    Comparer               = [EqualityComparerMy]::new()
}

Join-Object @Params | Format-Table

<#
IDD Name Junk IntT R_Sub R_IntO
--- ---- ---- ---- ----- ------
  1 A    AAA     5 S1         6
  3 C    S3        S1         6
  4 D              S4
#>
```

Basically in LeftJoinScript/RightJoinScript you return the thing to be compared, default is the LeftJoinProperty/RightJoinProperty as a string.
Then this items are send to the [EqualityComparer] that determine if they are equal, if not provided .NET will compare it similarly to `$LeftProperty.Equals($RightProperty)` I think.

In this example RightJoinScript is overridden to return objects (as by default it returns strings and the array in "ID" will be converted/corrupted),
Then the "EqualityComparerMy" is used to check if the left item is on the right array, if it is it will return `$true` and the rows will be joined.

Do you have something in mind that you will like to try? maybe we can make an example from that.
