### ISSUE TITLE
Errors When AddKey Parameter Contains a Space

### ISSUE THREAD

**Issue by franklesniak** [ili101/Join-Object#16]
Hi There,

I've noticed that when I run Join-Object and specify the -AddKey parameter with a space, e.g.:

`$CSVInterimResult = Join-Object -Left @($hashtableWMPInventoryComputers.Values) -Right @($hashtableSophosComputers.Values) -LeftJoinProperty 'Computer Name' -RightJoinProperty 'Name' -Type 'AllInBoth' -AddKey 'Computer Name' -ExcludeLeftProperties 'Computer Name' -ExcludeRightProperties 'Name'`

I get errors:

```
Exception calling "Create" with "1" argument(s): "At line:11 char:31
+             $RowMain.Computer Name = $Key
+                               ~~~~
Unexpected token 'Name' in expression or statement."
At C:\Program Files\WindowsPowerShell\Modules\Join-Object\2.0.2\Join-Object.ps1:772 char:9
+         [System.Func[System.Object, [Collections.Generic.IEnumerable[ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException

Join-Object : Cannot find an overload for "FullGroupJoin" and the argument count: "6".
At line:1 char:21
+ ... rimResult = Join-Object -Left @($hashtableWMPInventoryComputers.Value ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Join-Object], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest,Join-Object
```

On the other hand, if I run this same command without the space in the parameter, e.g.,:

`$CSVInterimResult = Join-Object -Left @($hashtableWMPInventoryComputers.Values) -Right @($hashtableSophosComputers.Values) -LeftJoinProperty 'Computer Name' -RightJoinProperty 'Name' -Type 'AllInBoth' -AddKey 'ComputerName' -ExcludeLeftProperties 'Computer Name' -ExcludeRightProperties 'Name'`

This works just fine.

**Comment by ili101** [comment]
I think I found it can you try this fix https://github.com/ili101/Join-Object/commit/9d5a29a855a3b04b4e9842cee70a164395014718 in Join-Object.ps1?
I will release a fixed version later.

**Comment by franklesniak** [comment]
That seems to have fixed it. Thanks for digging into this so quickly! I tested on PS 5.1 on WS2016.

**Comment by ili101** [comment]
I have changed the fix:
```powershell
# from
$RowMain.'YourKey'
# to
$RowMain.$AddKey

# DataTable 
# from
$RowMain['YourKey']
# to
$RowMain[$AddKey]
```
So it will work with things like `a 'a"a`

**Comment by ili101** [comment]
Released to gallery. please reopen if you find any issue

**Comment by franklesniak** [comment]
Awesome, thank you!
