### ISSUE TITLE
multiple column join

### ISSUE THREAD

**Issue by ericxin1982** [ili101/Join-Object#18]
Hi @ili101 

If I have multiple columns need to be joined, is it feasible? The example you gave is single column join.

Thanks
Eric Xin

**Comment by ili101** [comment]
If I understand you correctly as stated in the readme:
> -RightJoinProperty and -LeftJoinProperty supports multiple Properties (String Array) to join on multiple columns.

So `-RightJoinProperty 'Foo', 'Bar' -LeftJoinProperty 'Foo2', 'Bar2'` 

And If you need something more custom you can supply you own scriptblocks to extract the thing to be compared from the rows:
> -RightJoinScript and -LeftJoinScript parameters to support custom joining scripts.

`-RightJoinScript { param ($Line) $Line.Foo.Replace('ID-', '') + $Line.Bar } -LeftJoinScript ...`

**Comment by ericxin1982** [comment]
So it means, it would be matched the join order one by one, right?

**Comment by ili101** [comment]
It will concatenate the strings from the columns of the mentioned side (in the provided order), and use this as the thing to compare.
If it's not what you need maybe provide a simple example of the data and the expected output.

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/224886184-c5290c8f-16d7-469d-a574-7dd7cabcf460.png)

**Comment by ili101** [comment]
That error usually indicate that your -RightJoinProperty have duplicates in it (even after combining all these columns).
In this case you can add even more columns to make it unique, or fix the data by removing duplicates before using the function, or use `-RightMultiMode DuplicateLines` or `-RightMultiMode SubGroups`

**Comment by ericxin1982** [comment]
ok, it has output.
but the concern is like this, I am looking for the sql left join function from join-object.
![image](https://user-images.githubusercontent.com/9047436/224891351-c2874a65-fc5c-4dca-baee-6468a1879f8f.png)
I want to keep the $left rows unchanged, and #doc this column from $right left join into the $left.
![image](https://user-images.githubusercontent.com/9047436/224891399-67e3b605-b173-4fcf-914e-5fd65eef75e4.png)

Is it possible?

**Comment by ericxin1982** [comment]
-type allinleft this switch is there or not, does not change the output, it is duplicated still. Thanks.

**Comment by ericxin1982** [comment]
Join-Object -Left $left -right $right -LeftJoinProperty 'zip','customer','rectype','usstate' -RightJoinProperty 'zip','customer','rectype','usstate' -type AllInLeft -RightProperties '#doc' -LeftProperties *

I figured out, I saw internet has one article described your tool, I followed, it works.

Thanks for your help! Good tool!
