### ISSUE TITLE
Join-Object : Exception calling "SingleOrDefault" with "1" argument(s): "Sequence contains more than one element"

### ISSUE THREAD

**Issue by lukedaemon** [ili101/Join-Object#19]
Hello,
I'm using the Join-Object beween two **PSCustomObject**(s). 
They have these **NoteProperty**:

```
$First
"AAD.DeviceOSType","AAD.DeviceTrustType","AAD.DisplayName","AAD.LastLogonTimeStamp","AAD.RegisteredOwner","Company","EligibleForDeletion","Intune.Id","Intune.LastSyncDateTime","Intune.Model","Intune.PrimaryUser","Intune.SN","Intune.UPN","LastContactDateTime"

$Second
"AccountEnabled","Name","OU","UserPrincipalName"
```

The first PSCustomObject **$First** contains the list of Intune devices ("**primary key**": _Intune.SN_).
The second **$Second** the list of all Active Directory users ("**primary key**": _UserPrincipalName_). 
The resulting PSCustomObject should contain all columns from both objects and list of ALL Intune devices and ALL AD users. The join fields are: _Intune.PrimaryUser_ (**$First**) and _UserPrincipalName_ (**$Second**).
This is the Join-Object cmdlet:

`Join-Object -Left $First -Right $Second -LeftJoinProperty Intune.PrimaryUser -RightJoinProperty UserPrincipalName -Type AllInBoth `

I'm getting the error:

`Join-Object : Exception calling "SingleOrDefault" with "1" argument(s): "Sequence contains more than one element"`

Any advice ?

**Comment by ili101** [comment]
As you probably have multiple groups owned by the same user you have duplicate keys on the left.
In `-Type AllInBoth` this is forbidden by default https://github.com/ili101/Join-Object#default-and-supported-join-modes.
By your description I think you want to set `-LeftMultiMode DuplicateLines` so when the left have duplicate keys the right (user) will be cloned.
You can also use `-LeftMultiMode SubGroups` which will give you unduplicated users list with array of their groups (similar to `Group-Object` format)

**Comment by lukedaemon** [comment]
Simply great !!!

Thank you.
