### ISSUE TITLE
Join-Object does not run in powershell v4 enviornment

### ISSUE THREAD

**Issue by kcheng-didata** [ili101/Join-Object#7]
I have large data sets to be joined in the Exchange PowerShell environment which only uses PowerShell v4. I tried your script but it gave me errors. Does your script support PowerShell v4? If not, are you able to add the support?

Thanks!

**Comment by ili101** [comment]
PowerShell 4 Is not supported, Adding support for it is theoretically possible but I don't plan to add support for it as it will require to revert a lot of things to older syntax. And as VSCode plan to remove support for PowerShell 4 I don't want to support something I can't debug.

We can try the following ideas
1. If you want I can create a version for you that will partly work in PowerShell 4, not all parameters will work, no support.
2. You can upgrade to PowerShell 5.1 if your OS support that.
3. You can install PowerShell Core if your script will run on it.
4. You can try running your script as is, then export the data to a file, Run Join-Object in PowerShell Core, export to a file, and Import it back in your script. but I don't know how well it will work.
5. Use something else like the original Join-Object https://github.com/RamblingCookieMonster/PowerShell/blob/master/Join-Object.ps1 or the "Join" script from the PowerShell Gallery (I don't know if they work on PowerShell 4 or have the functionality you need)

**Comment by kcheng-didata** [comment]
It would be appreciated if you could create a version for PowerShell 4. As I am dealing with millions of records, performance is very important. I tried the original Join-object, the performance was very bad.

**Comment by ili101** [comment]
Try replacing with this file https://gist.github.com/ili101/0be72ab2633098f7e43f9da3e1ab8235
See if it work for what you need.
BTW my script works 70% faster on PowerShell Core VS 5.1, I don't know what is the performance hit in 4.0

**Comment by kcheng-didata** [comment]
Thanks, your script has worked and it's 3 times faster than the old one. Much appreciated!

**Comment by ili101** [comment]
👍
